# Generated by Django 2.0.4 on 2019-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trang', '0003_auto_20190212_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trangle',
            name='output',
            field=models.CharField(max_length=100),
        ),
    ]
