# Generated by Django 2.0.4 on 2019-02-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trang', '0004_auto_20190212_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trangle',
            name='output',
            field=models.CharField(choices=[('Scalene', 'Scalene'), ('Equilateral', 'Equilateral'), ('Isosceles', 'Isosceles'), ('Incorrect', 'Incorrect')], default='Scalene', max_length=100),
        ),
    ]
